// <auto-generated />
using EFCore_Loading_DataAnnotations_Examples;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore_Loading_DataAnnotations_Examples.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240813093357_add")]
    partial class add
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCore_Loading_DataAnnotations_Examples.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogId"));

                    b.Property<string>("BlogName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BlogId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            BlogId = 1,
                            BlogName = "GökçeBlog"
                        },
                        new
                        {
                            BlogId = 2,
                            BlogName = "MelisBlog"
                        });
                });

            modelBuilder.Entity("EFCore_Loading_DataAnnotations_Examples.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostId");

                    b.HasIndex("BlogId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            BlogId = 2,
                            Title = "C# nedir?"
                        },
                        new
                        {
                            PostId = 2,
                            BlogId = 1,
                            Title = "Front-End nedir?"
                        },
                        new
                        {
                            PostId = 3,
                            BlogId = 2,
                            Title = "Back-End nedir?"
                        },
                        new
                        {
                            PostId = 4,
                            BlogId = 1,
                            Title = "API nedir?"
                        });
                });

            modelBuilder.Entity("EFCore_Loading_DataAnnotations_Examples.Post", b =>
                {
                    b.HasOne("EFCore_Loading_DataAnnotations_Examples.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("EFCore_Loading_DataAnnotations_Examples.Blog", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
